```{r package, message=FALSE, warning=FALSE}
library(lubridate)
library(ggplot2)
library(forecast)  
library(Kendall)
library(tseries)
library(outliers)
library(tidyverse)
library(smooth)
```

#Neural Network

```{r}
#Neural Network 24
NN_scores24 <- accuracy(NN_forec_24$mean,ts_load_test)

#Neural Network 26
NN_scores26 <- accuracy(NN_forec_26$mean,ts_load_test)

#Neural Network 36
NN_scores36 <- accuracy(NN_forec_36$mean,ts_load_test)
```

#SARIMA

```{r}
SARIMA_scores <- accuracy(SARIMA_forec$mean, ts_load_monthly_test)
```

#SSES

```{r}
SSES_scores <- accuracy(SSES_forec$mean, ts_load_monthly_test )
```

#SSBM

```{r}
SSBM_scores <- accuracy(SS_forec$mean, ts_load_monthly_test )
```

#STL+ETS

```{r}
STL_ETS_scores <- accuracy(ETS_fit$mean, ts_load_test)
```

#TBATS

```{r}
TBATS_scores <- accuracy(TBATS_for$mean, ts_load_test)
```

#ARIMA+Fourier (without exogenous variables)
```{r}
#ARIMA Fourier 23
ARIMAFou_scores23 <- accuracy(ARIMA_Fourier_forec23$mean,ts_load_test)

#ARIMA Fourier 24
ARIMAFou_scores24 <- accuracy(ARIMA_Fourier_forec24$mean,ts_load_test)

#ARIMA Fourier 26
ARIMAFou_scores26 <- accuracy(ARIMA_Fourier_forec26$mean,ts_load_test)

#ARIMA Fourier 36
ARIMAFou_scores36 <- accuracy(ARIMA_Fourier_forec36$mean,ts_load_test)
```

```{r}
# Combine all scores into one data frame
ALLscores <- as.data.frame(
  rbind(NN_scores24, NN_scores26, NN_scores36, 
        SARIMA_scores, SSES_scores, SSBM_scores, 
        STL_ETS_scores, TBATS_scores, 
        ARIMAFou_scores23, ARIMAFou_scores24, ARIMAFou_scores26, ARIMAFou_scores36)
)

# Set row names to identify models
row.names(ALLscores) <- c("NN24", "NN26", "NN36", 
                          "SARIMA", "SSES", "SSBM", 
                          "STL+ETS", "TBATS", 
                          "AF23", "AF24", "AF26", "AF36")

# Save to CSV
write.csv(ALLscores, "ALLscores.csv", row.names = TRUE)
```


#Final Table with 6 models created
```{r}
# Create data frame
ALLscores <- as.data.frame(
  rbind(NN_scores24, NN_scores26, NN_scores36, SARIMA_scores, SSES_scores, SSBM_scores, STL_ETS_scores, TBATS_scores, ARIMAFou_scores23, ARIMAFou_scores24, ARIMAFou_scores26, ARIMAFou_scores36)
  )
row.names(ALLscores) <- c("NN24","NN26", "NN36", "SARIMA", "SSES", "SSBM", "STL+ETS", "TBATS", "AF23","AF24", "AF26", "AF36")

# Construct tables
kbl(ALLscores, 
      caption = "Forecast Accuracy for Daily Load",
      digits = array(5,ncol(ALLscores))) %>%
  kable_styling(full_width = FALSE, position = "center", latex_options = "hold_position") %>%
  kable_styling(latex_options="striped", stripe_index = which.min(scores[,"MAPE"]))
```


```{r}
# Create data frame
ALLscores <- as.data.frame(
  rbind(NN_scores24, NN_scores26, NN_scores36, STL_ETS_scores, TBATS_scores)
  )
row.names(ALLscores) <- c("NN24","NN26", "NN36", "STL+ETS", "TBATS")

# Construct tables
kbl(ALLscores, 
      caption = "Forecast Accuracy for Daily Load",
      digits = array(5,ncol(ALLscores))) %>%
  kable_styling(full_width = FALSE, position = "center", latex_options = "hold_position") %>%
  kable_styling(latex_options="striped", stripe_index = which.min(scores[,"MAPE"]))

write.csv(ALLscores, "ALLscores.csv", row.names = TRUE)
```

```{r}
autoplot(ts_load_test) +
  autolayer(ts_load_test, series = "Actual Load", color = "black", PI = FALSE) +
  autolayer(ARIMA_Fourier_forec23, series="Arima Fourier 23", PI=FALSE) +
  autolayer(ARIMA_Fourier_forec24, series="Arima Fourier 24", PI=FALSE) +
  autolayer(ARIMA_Fourier_forec26, series="Arima Fourier 26", PI=FALSE) +
  autolayer(NN_forec_24, series="Neural Network 24", PI=FALSE) +
  autolayer(NN_forec_26, series="Neural Network 26", PI=FALSE) +
  autolayer(NN_forec_36, series="Neural Network 36", PI=FALSE) +
  autolayer(ETS_fit, series="STL + ETS",PI=FALSE) +
  autolayer(TBATS_for, series="TBATS", PI=FALSE) +
  ylab("Load (MW)") +
  ggtitle("Model Comparison - Daily Forecasts")

autoplot(ts_load_monthly_test, series = "Actual Load", color = "black") +
  autolayer(SARIMA_forec, series = "SARIMA", PI=FALSE) +
  autolayer(SSES_forec, series = "SSES", PI=FALSE)  +
  autolayer(SS_forec, series = "SS BSM", PI=FALSE) +
  ylab("Monthly Load (MW)") +
  ggtitle("Model Comparison - Monthly Forecasts")


```

