
```{r Plot TS Fuels}
ts_data <- data.frame(
  time = time(ts_load),
  load = ts_load,
  temperature = ts_temp,
  coal_and_lignite = ts_coal_and_lignite,
  hydro = ts_hydro,
  nuclear = ts_nuclear,
  solar = ts_solar,
  wind = ts_wind,
  natural_gas = ts_natural_gas
)

autoplot(ts_natural_gas, series = "Natural Gas", size = 0.5, alpha = 0.6) +
  autolayer(ts_coal_and_lignite, series = "Coal and Lignite", size = 0.5, alpha = 0.8) +
  autolayer(ts_wind, series = "Wind", size = 0.3, alpha = 0.8) +
  autolayer(ts_nuclear, series = "Nuclear", size = 0.5, alpha = 0.8) +
  autolayer(ts_solar, series = "Solar", size = 0.5, alpha = 0.6) +
  autolayer(ts_hydro, series = "Hydro", size = 0.5, alpha = 0.6) +
  ggtitle("ERCOT Fuel Mix") +
  xlab("Time") +
  ylab("Load (MW)") +
  scale_color_manual(values = c("red", "darkgreen", "skyblue2", "midnightblue", "orange", "pink")) + 
  theme_minimal() +
  guides(colour = guide_legend(title = "Time Series"))
```
# TS Load

```{r TS ERCOT Load Plot}
autoplot(ts_load, series = "ERCOT Load") +
  ggtitle("ERCOT Load") +
  xlab("Time") +
  ylab("Load (MW)") +
  theme_minimal() +
  guides(colour = guide_legend(title = "Series"))
```

# Temp TS

```{r Temp TS}
autoplot(ts_temp) +
  ggtitle("ERCOT Area Temperature") +
  xlab("Time") +
  ylab("Temperature°F") +
  theme_minimal()
```

# Load ACF & PACF

```{r Load ACF & PACF}
# ACF and PACF for ERCOT Load
ggAcf(ts_load, lag.max = 365) + ggtitle("ACF of ERCOT Load") + theme_minimal()
ggPacf(ts_load, lag.max = 365) + ggtitle("PACF of ERCOT Load") + theme_minimal()
```

# Temp ACF & PACF

```{r Temp ACF & PACF}
# ACF and PACF for ERCOT Temperature
ggAcf(ts_temp, lag.max = 365) + ggtitle("ACF of ERCOT Temperature") + theme_minimal()
ggPacf(ts_temp, lag.max = 365) + ggtitle("PACF of ERCOT Temperature") + theme_minimal()
```

# ACF and PACF for Coal and Lignite

```{r ACF and PACF for Coal and Lignite}
# ACF and PACF for Coal and Lignite
ggAcf(ts_coal_and_lignite, lag.max = 365) + ggtitle("ACF of Coal and Lignite") + theme_minimal()
ggPacf(ts_coal_and_lignite, lag.max = 365) + ggtitle("PACF of Coal and Lignite") + theme_minimal()

```


# ACF and PACF for Hydro

```{r ACF and PACF for Hydro}
# ACF and PACF for Hydro
ggAcf(ts_hydro, lag.max = 365) + ggtitle("ACF of Hydro") + theme_minimal()
ggPacf(ts_hydro, lag.max = 365) + ggtitle("PACF of Hydro") + theme_minimal()
```

# ACF and PACF for Nuclear

```{r ACF and PACF for Nuclear}
# ACF and PACF for Nuclear
ggAcf(ts_nuclear, lag.max = 365) + ggtitle("ACF of Nuclear") + theme_minimal()
ggPacf(ts_nuclear, lag.max = 365) + ggtitle("PACF of Nuclear") + theme_minimal()
```

# ACF and PACF for Solar

```{r ACF and PACF for Solar}
# ACF and PACF for Solar
ggAcf(ts_solar, lag.max = 365) + ggtitle("ACF of Solar") + theme_minimal()
ggPacf(ts_solar, lag.max = 365) + ggtitle("PACF of Solar") + theme_minimal()
```

# ACF and PACF for Wind

```{r ACF and PACF for Wind}
# ACF and PACF for Wind
ggAcf(ts_wind, lag.max = 365) + ggtitle("ACF of Wind") + theme_minimal()
ggPacf(ts_wind, lag.max = 365) + ggtitle("PACF of Wind") + theme_minimal()
```

# ACF and PACF for Natural Gas

```{r ACF and PACF for Natural Gas}
# ACF and PACF for Natural Gas
ggAcf(ts_natural_gas, lag.max = 365) + ggtitle("ACF of Natural Gas") + theme_minimal()
ggPacf(ts_natural_gas, lag.max = 365) + ggtitle("PACF of Natural Gas") + theme_minimal()
```




































