```{r package, message=FALSE, warning=FALSE}
library(lubridate)
library(ggplot2)
library(forecast)  
library(Kendall)
library(tseries)
library(outliers)
library(tidyverse)
library(smooth)
library(zoo)
library(kableExtra)
```


```{r}
ERCOT_fuelmix$Date <- as.Date(ERCOT_fuelmix$interval_start_local)
ERCOT_load$Date <- as.Date(ERCOT_load$interval_start_local)

ERCOT_temp$Date <- as.Date(ERCOT_temp$interval_start_local)
ERCOT_temp$Average <- rowMeans(ERCOT_temp[,7:14], na.rm = FALSE, dims = 1)
ERCOT_temp_daily <- ERCOT_temp %>% 
  group_by(Date) %>% 
  summarise(mean(Average)) %>% 
  ungroup()

ts_load <- msts(ERCOT_load$load, seasonal.periods = c(7,365.25), 
                start = c(2017,1,1))
ts_temp <- msts(ERCOT_temp_daily[,2], seasonal.periods = c(7,365.25), 
                start = c(2017,1,1))
ts_coal_and_lignite <- msts(ERCOT_fuelmix$coal_and_lignite, seasonal.periods = c(7,365.25), 
                start = c(2017,1,1))
ts_hydro <- msts(ERCOT_fuelmix$hydro, seasonal.periods = c(7,365.25), 
                start = c(2017,1,1))
ts_nuclear <- msts(ERCOT_fuelmix$nuclear, seasonal.periods = c(7,365.25), 
                start = c(2017,1,1))
ts_solar <- msts(ERCOT_fuelmix$solar, seasonal.periods = c(7,365.25), 
                start = c(2017,1,1))
ts_wind <- msts(ERCOT_fuelmix$wind, seasonal.periods = c(7,365.25), 
                start = c(2017,1,1))
ts_natural_gas <- msts(ERCOT_fuelmix$natural_gas, seasonal.periods = c(7,365.25), 
                start = c(2017,1,1))

```

```{r}
autoplot(ts_load)
```

#Train/test Split
```{r}
n_for <-  365

ts_load_train <- subset(ts_load,end = length(ts_load)-n_for) #stops 365 days before

#create a subset for testing purpose
ts_load_test <- subset(ts_load, start = length(ts_load)-n_for) #last 365 observations

autoplot(ts_load_train)
autoplot(ts_load_test)
```

